--- # Demo for debug and register statement
- hosts: groupA
  remote_user: aswarns
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  tasks:
  - name: Installing telnet pkg
    yum:
      name: telnet
      state: latest
    register: result
  - debug: var=result
